bf16: true
cutoff_len: 1024
dataset: puyi_data
dataset_dir: data
ddp_timeout: 180000000
do_train: true
enable_thinking: true
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 0.0003
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: baidu/ERNIE-4.5-0.3B-PT
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves/ERNIE-4.5-0.3B-PT/lora/train_2025-12-23-08-34-28
packing: false
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: default
trust_remote_code: true
warmup_steps: 0
